### PR TITLE
Only mirror 7.0.1xx branch

### PR DESCRIPTION
**Pull request by mmitche**

### CODE REVIEW

**Review by vlada-shubina — APPROVED** [review]
Looks good

**Comment by vlada-shubina** [comment]
@mmitche a question: if I understand correctly, with this change the release/7.0.2xx will never be mirrored to internal/release/7.0.2xx.

So if we ever need to do the change internally, we need to reenable it back, correct?

**Comment by mmitche** [comment]
> @mmitche a question: if I understand correctly, with this change the release/7.0.2xx will never be mirrored to internal/release/7.0.2xx.
> 
> So if we ever need to do the change internally, we need to reenable it back, correct?

Correct. That's also the case for the internal->internal subscription.

**Comment by vlada-shubina** [comment]
@YuliiaKovalova just fyi

**Pull request merged**
