### PR TITLE
Adding auto update support for WCF master branch.

### PR DESCRIPTION
**Pull request by StephenBonikowsky**

### CODE REVIEW

**Comment by StephenBonikowsky** [comment]
@dagood @MattGal 

Auto formatting removed some commas, is that ok?

**Comment by MattGal** [comment]
Removing the extras doesn't really matter, but it's actually usually a good thing to have the extra commas so that it doesn't break later on a merge.

**Comment by StephenBonikowsky** [comment]
Ok, thanks, next time I'll limit the edits to my changes.

**Comment by MattGal** [comment]
If you just always run it through a JSON formatter and only you edit it, you'll be fine.

**Comment by dagood** [comment]
I think the particular JSON formatter Stephen used was what removed the `,`'s in the first place. :smile: I do usually pick through my diffs and revert stuff before submitting PRs, but that's not always easy depending on your workflow.

**Comment by MattGal** [comment]
right but such a formatter, if run on post-bad-merge json, would hopefully explode.

**Comment by dagood** [comment]
Ok, I think I misunderstood "you'll be fine".

**Comment by MattGal** [comment]
Right, 'You'll be fine... because errors will be caught.'

**Pull request merged**
