### PR TITLE
Restrict merge mirroring to avoid staging branches.

### PR DESCRIPTION
**Pull request by mmitche**

### CODE REVIEW

**Review by hoyosjs — APPROVED** [review]

**Review by carlossanlop — APPROVED** [review]
Interesting that a trailing `/` is enough to indicate end of branch name.

**Comment by mmitche** [comment]
It's because of how the comparisons are done. They're just a "StartsWith" without the `/**/*` removed from the end. The strings that are matched include the branch name and files changed. e.g. https://github.com/dotnet/versions/blob/main/Maestro/subscriptions.json`. So if you add an extra slash, it keeps the string from matching `https://github.com/dotnet/versions/blob/main-other/Maestro/subscriptions.json`

**Comment by dougbu** [comment]
> It's because of how the comparisons are done. They're just a "StartsWith" without the `/**/*` removed from the end. &hellip;

I think you mean _with_ the `/**/*` removed from the test string.

In any case, why isn't our default to remove only `**/*`❔ That would avoid some confusion and eliminate a need for the `//**/*` oddities in the JSON file.

**Comment by mmitche** [comment]
@dougbu Unknown. It's just the way it was written. That said, this is all getting rewritten and the new mode supports regex for real.

**Pull request merged**
