### PR TITLE
Add AspNetLatestChannel for 'latest' blob updates from prodcon

### PR DESCRIPTION
**Pull request by mmitche**

### CODE REVIEW

**Comment by dagood** [comment]
I don't know if I'm up to date on what this will do right now. Does this mean https://github.com/dotnet/core-eng/issues/2691 is maybe being solved?

**Comment by mmitche** [comment]
@dagood Actually we're juist going to leave it how it is right now for ASPNet.

**Comment by natemcmaster** [comment]
Yup, we're planning to use aka.ms links instead

**Comment by natemcmaster** [comment]
Actually, there is still one piece we need prodcon to update. We will need this file to be updated. It's used by the dotnet-install.ps1 script.

https://dotnetcli.blob.core.windows.net/dotnet/aspnetcore/Runtime/release/2.1/latest.version

**Pull request closed without merging**
