### PR TITLE
Update Roslyn versions

### PR DESCRIPTION
**Pull request by agocke**
Update Roslyn NuGet versions to 1.3.0-beta1-20160602-01.

### CODE REVIEW

**Comment by joshfree** [comment]
@agocke is this your "escrow" build or just the latest release build?  /cc @VSadov @eerhardt

**Comment by agocke** [comment]
@joshfree This is suitable as an escrow candidate for 1.3, but it's definitely not the last build -- we know further changes are incoming.

**Comment by joshfree** [comment]
thinking about this morning, we should have Roslyn rebuild on corefx's Fri-7pm build and then update core-setup with both payloads monday morning -- as part of moving all upstack teams to a newer build next week.

**Comment by joshfree** [comment]
either way we should merge this :)

**Comment by agocke** [comment]
@joshfree Up to you and @eerhardt. I don't have permissions on this repo :)

**Pull request merged**
