### PR TITLE
Add temporary final publishing for 2.1.2

### PR DESCRIPTION
**Pull request by mmitche**

### CODE REVIEW

**Comment by mmitche** [comment]
@dagood Do you think we need the symbol + blob publish in this or has that already been taken care of?

**Comment by dagood** [comment]
I performed and verified symbol publish for all the recent releases at the same time, including 2.1.2.

I know enough happened for the blobs to be usable for the release, but I don't know if there are gaps. @MichaelSimons do you know if there's anything to do there?

(And yeah, publishing to MyGet and the blob feed is desired since some places don't have a dependency on nuget.org. I don't know where these are off the top of my head though.)

**Comment by dagood** [comment]
Also @leecow for this question:

> I know enough happened for the blobs to be usable for the release, but I don't know if there are gaps.

**Comment by MichaelSimons** [comment]
I am not aware of anything from the Docker consumption standpoint.  @leecow would be the one who should be able to better answer.

**Comment by mmitche** [comment]
@dagood Updated to only have package + symbol publish

**Comment by leecow** [comment]
I don't think we had any gaps in blob asset movement this time other than a lack of automation for a bunch of it.

**Pull request merged**
