### PR TITLE
Add mirror for Standard -> Azure DevOps

### PR DESCRIPTION
**Pull request by wtgodbe**
Add mirror to Azure DevOps for Standard. Note that I'm only using the `AzureCi` branch to test changes to the pipebuild, and will remove that line once my pipebuild changes are in master. I'll put up an issue in `core-eng` for this & assign it to myself.

### CODE REVIEW

**Comment by wtgodbe** [comment]
@mmitche @dagood @natemcmaster PTAL

**Comment by wtgodbe** [comment]
Actually, if I'll have permissions to do so, I can just manually push the `AzureCi` branch to the repo once the first mirror has run, and remove the line now - will I have those permissions?

**Comment by mmitche** [comment]
@wtgodbe You should have them.

**Comment by wtgodbe** [comment]
@mmitche sounds good, I removed the line. Is this alright to go in?

**Pull request merged**
