### PR TITLE
Set SDK merging to 3.1.3xx-> 5.0.1xx-preview 3-> master

### PR DESCRIPTION
**Pull request by sfoslund**

### CODE REVIEW

**Comment by wli3** [comment]
@wtgodbe could you rerun the build, approve and merge it?

**Comment by mmitche** [comment]
@sfoslund @wli3 I don't think this is the right merge pattern. 3.1.3xx finishes well after preview3 ships. Also sdk in 3.1.3xx is very different from the 5x branches...would this even work well?

If anything, it should be 3.1.3xx->master

**Comment by wli3** [comment]
3.1.3xx merge to master could work. All the SDK changes can get there (CLI has far less code change during this time).

3.1.3xx will not finish, you mean 5.0.100-preview3? 5.0.100-preview3 will finish after preview 3 ships, but all the latest changes would go to that branch instead of the master. So we need to merge it to master to keep master up-to-date.

**Comment by mmitche** [comment]
> 3.1.3xx merge to master could work. All the SDK changes can get there (CLI has far less code change during this time).
> 
> 3.1.3xx will not finish, you mean 5.0.100-preview3? 5.0.100-preview3 will finish after preview 3 ships, but all the latest changes would go to that branch instead of the master. So we need to merge it to master to keep master up-to-date.

I mean that the next 3.1.3xx release will happen well after 5.0-preview3 ships. Meaning that relying on a merge to the preview3 branch and then to master will have to change once we move to preview4 (which is in ~3 weeks).

As an aside..what's the value of doing this? What % of real changes going into 3.x also apply to 5.x?

**Comment by wli3** [comment]
We don't want to triple check in any new change. And if we forget to do triple checkin, there is no system to catch it.

Implicit version change can flow through branch merges

Also we can just close the auto PR if there is no real changes

**Comment by mmitche** [comment]
Okay, just be sure not to destabilize the p3 branches at the end with unnecessary commits. That means that master will probably have to wait till after p3 is done to get the 3.1.3xx changes, once we lock down the branch (after the 17th)

**Pull request merged**
