### PR TITLE
Merge 3.1 -> blazor-wasm -> master in AspNet repos

### PR DESCRIPTION
**Pull request by wtgodbe**
@JunTaoLuo @dougbu PTAL

### CODE REVIEW

**Comment by JunTaoLuo** [comment]
cc @javiercn maybe this is the secret sauce we need.

**Comment by javiercn** [comment]
I think do

**Comment by dougbu** [comment]
Note this will not
1. merge directly from our 'release/2.1' branches to 'release/3.1'
2. do anything about issues w/ merges from 'release/3.1' to 'blazor-wasm' where we have 'blazor-wasm' branches
  - I've seen such merges but the branches might be too far out of sync due to incorrect merges or some such

**Comment by wtgodbe** [comment]
I've updated the PR to also merge directly from 2.1 -> 3.0, skipping 2.2. @javiercn @JunTaoLuo I also don't think this will fix issues merging 3.1 -> blazor-wasm. It will just make it so that we go from 3.1 -> blazor-wasm -> master, rather than 3.1 going to both places.

**Comment by wtgodbe** [comment]
@javiercn @JunTaoLuo - this should now just merge rel/3.1 -> blazor-wasm -> master for AspNetCore.

**Pull request merged**
