### PR TITLE
Update Microsoft.DiaSymReader

### PR DESCRIPTION
**Pull request by cston**
Update Microsoft.DiaSymReader to 1.0.8-rc2-60610-01

### CODE REVIEW

**Comment by cston** [comment]
@eerhardt, @tmat, @joshfree please review.

**Comment by tmat** [comment]
@cston Could you also add ```LKG_Packages.txt``` file with the same content? Thanks

**Comment by eerhardt** [comment]
LGTM. Let me know when the build is ready, and I'll merge.

**Comment by cston** [comment]
@eerhardt The build is ready.

**Pull request merged**
