### PR TITLE
Seed the projectn-tfs-ilc/arm64 version information

### PR DESCRIPTION
**Pull request by zamont**
Also correct the projectn-tfs-ilc/master version information.

### CODE REVIEW

**Comment by zamont** [comment]
@nattress @dagood Can you take a look? This is a pre-requisite for getting up our parallel arm64 build updated automatically.

**Comment by nattress** [comment]
Looks good to me!

**Comment by zamont** [comment]
@dagood I can't merge the change myself: `Only those with write access to this repository can merge pull requests`

Could you do the honors?

**Comment by dagood** [comment]
Done. Wanted to merge this and https://devdiv.visualstudio.com/DevDiv/_git/DotNetCore/pullrequest/107251 at around the same time so these changes don't get accidentally reverted by the infra. :smile:

**Comment by zamont** [comment]
Great, thanks for being on top of it 😃

**Pull request merged**
