### PR TITLE
Update subscriptions for dotnet/llvm-project

### PR DESCRIPTION
**Pull request by akoeplinger**
We're following a new branching structure to avoid confusion with upstream branches.

### CODE REVIEW

**Comment by akoeplinger** [comment]
@dotnet/dnceng

**Comment by lpatalas** [comment]
@akoeplinger I'm on FR now but I'm not too familiar with the area so maybe better if someone else takes a look when they're online?

Just to note - one potential issue that I see here is that Helix does job redirection to servicing queues based on the branch name. We compare prefixes so if we run on `dotnet/release` instead of `release/` then the job won't be redirected to servicing queue. We should probably adjust it in the Helix API if we go this way.

/cc @ulisesh / @MattGal

**Comment by akoeplinger** [comment]
@lpatalas ah interesting, I wasn't aware of that. I think we could also make `release/dotnet/6.0` instead to keep the pattern.

**Comment by akoeplinger** [comment]
Though we're not using Helix in the llvm-project repo so it doesn't matter here, but I guess similar logic might exist in other systems right?

**Comment by lpatalas** [comment]
This redirection is a Helix specific functionality so if Helix is not used here then I think it shouldn't be a problem.

**Review by mmitche — APPROVED** [review]

**Comment by akoeplinger** [comment]
Ok we discussed and we'd like to keep the proposed structure, so please merge it if no one has objections :)

**Comment by MattGal** [comment]
> This redirection is a Helix specific functionality so if Helix is not used here then I think it shouldn't be a problem.

Even if they do end up using Helix, the only issue that would fall out is running the tests on the main environment versus the servicing ones; this is purely for billing and since llvm is much, much smaller than any of the major teams its Helix testing would basically be a rounding error next to the big repos like runtime / aspnetcore.

**Pull request merged**
