### PR TITLE
Disable per-PR builds of Core-Setup 1.1.0/1.0.0

### PR DESCRIPTION
**Pull request by wtgodbe**
CC @gkhanna79 @dagood - let's merge this at 6 PST tonight, 2/8/2017

### CODE REVIEW

**Comment by wtgodbe** [comment]
@dagood I don't have permission to merge this, can you do the honors?

**Comment by gkhanna79** [comment]
I just merged it.

**Comment by gkhanna79** [comment]
@wtgodbe Are the CoreCLR and CoreFX 1.0.x and 1.1.x builds disabled?

**Comment by wtgodbe** [comment]
@gkhanna79 yes, I disabled them about an hour ago.

**Pull request merged**
