### PR TITLE
Change sdk master to main

### PR DESCRIPTION
**Pull request by marcpopMSFT**

### CODE REVIEW

**Comment by marcpopMSFT** [comment]
@dotnet/dnceng Step 3 of the master to main rename.  I've confirmed that my change to .vsts-ci.yml has shown up in the ADO dnceng repo.

**Review by premun — APPROVED** [review]

**Comment by marcpopMSFT** [comment]
@dotnet/dnceng I assume I should halt proceeding on the remaining steps until this can be merged, correct?  I see that the dotnet-versions-public-ci pipeline is delayed at the moment as I'm number 751 in the queue.  :(

**Comment by premun** [comment]
@marcpopMSFT unfortunately, you need to halt, yes.

The large queue is caused by AzDO service degradation: https://status.dev.azure.com/_event/232594872

**Comment by mmitche** [comment]
IIRC all that pipeline does is compile old Maestro, and maaaaaybe checks that the json parses.

**Comment by marcpopMSFT** [comment]
@dotnet/dnceng Test passed. I don't have write access to this repo.  Can you please merge so I can continue the steps?

**Pull request merged**
