### PR TITLE
Revert "Add auto-merge from Master into Release/3.0"

### PR DESCRIPTION
**Pull request by wtgodbe**
Reverts dotnet/versions#442

We'll do this weekly in AzDO instead

### CODE REVIEW

**Comment by mmitche** [comment]
@dagood We stopped this for the core* repos for now.  master and 3.0 will end up having identical sources, and I got complaints upstack that there is a ton of changes generated off of this which then cause merge conflicts for automatic PRs going back into master.

**Comment by dagood** [comment]
That's fine by me. Not sure if I fully get this:

> I got complaints upstack that there is a ton of changes generated off of this which then cause merge conflicts for automatic PRs going back into master.

Is this saying master => release/3.0 merges being done in CoreCLR/FX/Setup were causing changes in downstream repos that were causing merge conflicts in their release/3.0 => master auto-PRs? I don't understand why the merges in Core\* would cause more merge conflicts downstream than the changing versions from daily builds would.

Or does this go further, and we're actually shutting down the Core\* `release/3.0` builds entirely right now?

**Comment by mmitche** [comment]
Yeah, shutting down release/3.0 builds for now.  There is no real reason for them.  What happens is that we build here, the changes flow downstream into the release branches, and then those repos have auto-merges back into master after they get checked in.  These changes always conflict in eng/Version,.Details.xml (because .NET Core 3 Dev is flowing into master).  This is fine while we're actually needing to produce 3.0 release builds.  But for now it just causes a lot of extra work.  A single core-setup change generates another 10-20 commits that need to be dealt with.

**Comment by dagood** [comment]
Sounds good to me. FWIW basically the same the merge conflicts happen in Core\* too, although at a lesser scale--the upstack distinction was my initial confusion.

**Pull request merged**
