### PR TITLE
Maestro handler to update docker-nightly rel-1.0.0-preview2.1 artifacts

### PR DESCRIPTION
**Pull request by MichaelSimons**
@naamunds, @dagood

### CODE REVIEW

**Comment by dagood** [comment]
Waiting to merge for changes to the auto-update script: the desire is to have two separate "live" PRs.

**Comment by naamunds** [comment]
This will need to be merged with the subscriptions.json refactor.

**Comment by MichaelSimons** [comment]
@dagood, the [corresponding changes](https://github.com/dotnet/dotnet-docker-nightly/pull/88) to the auto-update script were made.  Additionally I merged these changes with the latest subscriptions.json refactor.

If these changes are satisfactory, please merge.

**Comment by dagood** [comment]
Looks good, thanks, merging.

**Pull request merged**
