### PR TITLE
Manually publish BuildTools preview1-03706-01

### PR DESCRIPTION
**Pull request by tannergooding**
Buildtools wasn't able to publish this itself. Doing it manually to flow the new version through the upgrade infra.

The build: https://devdiv.visualstudio.com/DevDiv/_build/results?buildId=2388726

### CODE REVIEW

**Comment by tannergooding** [comment]
CC. @dagood 

Looks like this failed due to:
> Encountered exception committing build-info update: Response code does not indicate success: 422 (422) with content: {"message":"Must supply tree.sha or tree.content","documentation_url":"https://developer.github.com/v3/git/trees/#create-a-tree"}

**Comment by tannergooding** [comment]
@dagood, is there anything preventing this from pushing out to repos?

I would have expected a PR against CoreCLR master branch (given that I also saw one for the feature/utf8string branch already). All the appropriate entries still look to exist and I haven't seen any changes to these files since the last manual push happened 20 days ago (in which case the corresponding updates were created by dotnet-maestro-bot).

**Comment by dagood** [comment]
Looks like the upgrade command is failing: https://devdiv.visualstudio.com/DevDiv/_build/results?buildId=2391087.

```
##[error]& : The term 'E:\A\_work\4375\s\run.cmd' is not recognized as the name of a 
cmdlet, function, script file, or operable program. Check the spelling of the 
name, or if a path was included, verify that the path is correct and try again.
At line:1 char:3
+ & "E:\A\_work\4375\s\run.cmd" build -Project='tests\build.proj' -- /t ...
+   ~~~~~~~~~~~~~~~~~~~~~~~~~~~
    + CategoryInfo          : ObjectNotFound: (E:\A\_work\4375\s\run.cmd:Strin 
   g) [], CommandNotFoundException
    + FullyQualifiedErrorId : CommandNotFoundException
```

run.cmd was removed with https://github.com/dotnet/coreclr/pull/21608, breaking the current subscription command. It's defined here:

https://github.com/dotnet/versions/blob/76a1a04b1a3a219214a482eb82df13093905d357/Maestro/subscriptions.json#L173-L187

Should be reasonable to replace... to test locally, just run `/t:UpdateToRemoteDependencies` without the other props--if the basic command works, the other properties should pass in and to the PR submission fine.

**Comment by dagood** [comment]
For example, corefx got their PR: https://github.com/dotnet/corefx/pull/35139. The subscription there is:

https://github.com/dotnet/versions/blob/76a1a04b1a3a219214a482eb82df13093905d357/Maestro/subscriptions.json#L438-L448

**Pull request merged**
