### PR TITLE
Disable 3.0 -> 3.1 auto-merges during Preview3 build window

### PR DESCRIPTION
**Pull request by wtgodbe**
CC @Anipik @livarcocc @nguerrera @dagood @dougbu 

I'll merge this Sunday, then revert it after we declare a final build for GA

### CODE REVIEW

**Comment by nguerrera** [comment]
Do you also want to do this for cli/sdk/toolset/core-sdk? We just moved to this bot but our entries are elsewhere since our branches are differently named.

**Comment by wtgodbe** [comment]
> Do you also want to do this for cli/sdk/toolset/core-sdk? We just moved to this bot but our entries are elsewhere since our branches are differently named.

Yes, thanks for the heads up. Just pushed a commit

**Comment by nguerrera** [comment]
Seems that we should have an enabled: false or something instead of making revert noise in the history

**Comment by wtgodbe** [comment]
> Seems that we should have an enabled: false or something instead of making revert noise in the history

@dagood do you know if there's a way to do this?

**Comment by nguerrera** [comment]
Makes it hard to reference what is authored at any time. 

Even better would be something on the backend that can disable.

**Comment by dagood** [comment]
I think the best you can do with what's implemented right now is comment out the triggers or something along those lines. The code is at https://github.com/dotnet/versions/tree/master/Maestro/src if you'd like to browse/contribute. Note that core-eng has to manually deploy changes and they may have a high bar, although this change would be trivial in terms of code.

Core-eng is targeting getting this functionality off Maestro somehow. https://github.com/dotnet/arcade/issues/405 (don't know if there's an active tracker)

**Comment by dagood** [comment]
> Even better would be something on the backend that can disable.

The build def or branch merge script could do some additional logic to no-op itself based on external data. Maybe search for the last auto-merge PR with the same config, see if it has a "don't" tag?

Could just add another json file to this repo that contains streamlined branch-merge-specific enable/disable info, something like that.

**Comment by nguerrera** [comment]
Is this already off somehow, I was waiting for a merge from 3.0 -> 3.1 of core-sdk to get some goodness for our CI flakiness.

**Comment by wtgodbe** [comment]
It shouldn't be, how recently was the commit merged into 3.0? If it was before you added the SDK repos here (3 days ago), the builds wouldn't have been triggered. They only run when a new commit gets merged into a trigger branch

**Comment by nguerrera** [comment]
It was this morning. The triggers have been working.

**Comment by wtgodbe** [comment]
Weird. You can always run https://dnceng.visualstudio.com/internal/_build?definitionId=350 manually

**Comment by nguerrera** [comment]
Oh, it's failing.

**Comment by nguerrera** [comment]
https://dnceng.visualstudio.com/internal/_build/results?buildId=411827&view=logs&j=275f1d19-1bd8-5591-b06b-07d489ea915a

**Comment by nguerrera** [comment]
Oh, if I merge an existing PR that it failed to update, then it doesn't trigger again. for things that came up when it failed to update I guess. Hmm.

**Comment by nguerrera** [comment]
OK, I triggered it, and I see the issue. I will log something, but I'm unblocked.

**Pull request merged**
