### PR TITLE
Disable auto-PRs for new release/1.0.0 versions

### PR DESCRIPTION
**Pull request by dagood**
Instead of closing PRs like https://github.com/dotnet/corefx/pull/9366, disables the source.

/cc @eerhardt @ericstj @stephentoub

### CODE REVIEW

**Comment by stephentoub** [comment]
LGTM

**Comment by ericstj** [comment]
LGTM

**Comment by gkhanna79** [comment]
@dagood Should we do this for CoreCLR as well?

CC @joshfree @Petermarcu @sergiy-k @eerhardt

**Comment by dagood** [comment]
This PR disabled **all** automatic release/1.0.0 dependency updates, including the CoreCLR dependency on External (TFS). I didn't make a clear description, sorry--if this cast too wide of a net (maybe we still wanted build pipeline auto-PRs?) I can revert parts of it.

**Comment by gkhanna79** [comment]
Thanks for the confirmation @dagood - this sounds good then!

**Pull request merged**
