### PR TITLE
Update subscriptions for dotnet/icu

### PR DESCRIPTION
**Pull request by directhex**
We're following a new branching structure to avoid confusion with upstream branches.

### CODE REVIEW

**Comment by directhex** [comment]
@dotnet/dnceng

**Comment by premun** [comment]
Is this the same case like https://github.com/dotnet/versions/pull/823?

**Comment by premun** [comment]
Specifically I am asking about whether icu is also small enough so that we don't care that Helix jobs from the repo won't go into the servicing queues

**Comment by directhex** [comment]
Yep, exactly the same

**Comment by directhex** [comment]
We don't run Helix tests on dotnet/icu

**Review by premun — APPROVED** [review]

**Pull request merged**
