### PR TITLE
Removing stale SDK interbranch merge rules

### PR DESCRIPTION
**Pull request by sfoslund**

### CODE REVIEW

**Comment by sfoslund** [comment]
@wli3 I'm removing this since it's outdated, but let me know if you think we should update to the latest preview instead

**Comment by wli3** [comment]
Let's remove them. It is too hard to keep moving to new branches. And so far I don't see we missed anything

**Comment by wli3** [comment]
@wtgodbe could you merge this change?

**Comment by wtgodbe** [comment]
You could do what Asp.Net does to merge any 5.0-preview branch back to master:

https://github.com/dotnet/versions/blob/acc3af64db7225913b18a14dfc641f64acda85bf/Maestro/subscriptions.json#L1018-L1036

**Comment by sfoslund** [comment]
Merging all 5.0-preview* branches to master sounds fine to me. Any objections, @wli3?

**Comment by wli3** [comment]
let's see. If we have a last merge for them, it should be fine. If not, there will be a wave of PRs, and we have to resolve them (instead of close). And merge them. Then, they won't show up.

**Comment by sfoslund** [comment]
We'll need to do those merges eventually anyway, so might as well get the bot to make them and the vendors to help out, right?

**Pull request merged**
