### PR TITLE
Revert "Disable mirror for 2.1"

### PR DESCRIPTION
**Pull request by mmitche**
This reverts commit c7dd1f1d14abd17decbafdb712e65fea7cf323fb.

Also adds core-setup mirror

### CODE REVIEW

**Comment by mmitche** [comment]
@weshaggard Any idea why there wasn't a core-setup mirror before?

**Comment by weshaggard** [comment]
>@weshaggard Any idea why there wasn't a core-setup mirror before?

It is because we never needed an internal fork of the core-setup branches and always just used the public repo.

**Comment by wtgodbe** [comment]
@mmitche is this good to merge? Also, how can I manually queue a mirror build to get github changes into the internal branches? When I queued one for CoreClr release/1.0.0 it only mirrored into the normal VSTS branch. Should I just run the steps from the job locally?

**Pull request merged**
