### PR TITLE
Setup Maestro for uwp-setup repo

### PR DESCRIPTION
**Pull request by zamont**
Adds a new Maestro subscription for the uwp-setup repo. Adds triggers for the uwp-setup master branch and arm64 branch.

### CODE REVIEW

**Comment by zamont** [comment]
/cc: @nattress @dagood 

Apologies for the duped PR. I left my work on my fork's master branch which I overwrote. Davis, you had a comment on the previous PR regarding https://github.com/dotnet/uwp-setup/blob/master/dependencies.props that you'll have to remind me of.

**Comment by dagood** [comment]
Should still be able to see it here: https://github.com/dotnet/versions/pull/228#discussion_r167975899. Basically, the triggers here and `RemoteDependencyBuildInfo`s in the repo should generally match so you get predictable update PR submissions.

**Comment by zamont** [comment]
That makes sense. So what we are trying to do is not actively update CoreFx and WCF because those dependencies will be specified in our new Microsoft.Private.NetNative.Framework package. For that reason, I've excluded the dotnet/versions triggers for those two repos.

It seems to me the only work item for me is to go back to uwp-setup:dependencies.props and remove the `RemoteDependencyBuildInfo`s and `XmlUpdateStep`s for CoreFx and WCF. Does that sound right to you?

**Comment by dagood** [comment]
Plan makes sense to me!

That's right, and ideally the `CurrentRef`s and `PackageVersion` properties to keep it tidy.

**Comment by zamont** [comment]
Davis, can you go ahead and merge this?

**Comment by dagood** [comment]
Sure, noticed it's ported to the `arm64` branch too.

**Pull request merged**
