### PR TITLE
Add Latest_Packages.txt for new master cli branch

### PR DESCRIPTION
**Pull request by eerhardt**
New cli branch - https://github.com/dotnet/cli/tree/master

@dagood

### CODE REVIEW

**Comment by dagood** [comment]
The file actually needs to be entirely blank--VersionTools chokes on a blank line with no package on it.

**Comment by eerhardt** [comment]
blek

**Comment by eerhardt** [comment]
fixed.  thanks for the heads-up @dagood

**Comment by dagood** [comment]
No problem. Merging.

**Pull request merged**
